gov_uk_dashboards/components/plotly/phase_banner.py
setup.py

Added a **phase banner component**, matching the Gov.UK Design System component here: https://design-system.service.gov.uk/components/phase-banner/
This is intended to be used to collect feedback from users while our dashboards are being developed.
It allows you to set the phase (e.g. alpha, beta) and set a link to collect feedback, which can be mailto: link to create a template e-mail. Also included a settable id for the link so the link address can be targeted by callbacks, which will allow the subject of the e-mail generated to be set according to which dashboard page the user is currently on (along with potentially other things if we wanted).

Add phase banner component for collecting feedback

---

gov_uk_dashboards/components/plotly/details.py
gov_uk_dashboards/components/plotly/footer.py
setup.py

Added two components we created as part of LearnTech Friday:
A 'details' component, potentially useful for providing explanatory information regarding some of our technical terms.
A footer in the Gov.UK style.

Added details and footer components

---

gov_uk_dashboards/components/plotly/table.py
setup.py

Added component to display pandas DataFrames as HTML tables in the [Gov.UK Design System style](https://design-system.service.gov.uk/components/table/).
Includes options to include a title, whether the first column is treated as a header column, and whether to include the column labels as headers.
I intend to make use of this in [this ticket](https://trello.com/c/flKZLMX0).

Added table component for displaying dataframes

---

README.md
environment.yml
gov_uk_dashboards/formatting/human_readable.py
setup.py
tests/unit_tests/gov_uk_dashboards/formatting/test_format_as_human_readable.py

Adds a function to turn values into human readable versions.
E.g.
1,200,000,000 -> 1.2bn
252,000 -> 252k
Can add a prefix as well for convenience, such as '£'

Add human readable formatting function to pkg

---

environment.yml
gov_uk_dashboards/formatting/human_readable.py
gov_uk_dashboards/formatting/rounding.py
setup.py
tests/unit_tests/gov_uk_dashboards/formatting/test_format_as_human_readable.py
tests/unit_tests/gov_uk_dashboards/formatting/test_round_thousands_to_1dp.py

Added commonly used rounding functionality to the formatting in the package.
- round_thousands_to_1dp has been added, to round figures to 1dp in steps of a thousand. This previously has been in our Local Government Dashboard, but seemed sensible to add here as generally useful functionality
- format_as_human_readable now has two new optional arguments, decimal_places (which sets the decimal places to round to) and suffix (for adding stuff like '%' or 'per annum' after the number).
Also added tests for the new function/functionality

Add rounding functionality to formatting

---

gov_uk_dashboards/components/plotly/table.py
setup.py

Added an optional argument to table_from_dataframe allowing for a smaller title where desired. Doesn't break backward compatibility.

Add argument to table to allow sizing the title

---

gov_uk_dashboards/formatting/human_readable.py
tests/unit_tests/gov_uk_dashboards/formatting/test_format_as_human_readable.py

If format_as_human_readable is called with None or Nan then return a separator of "-". The separator can be overridden with a user desired value

return "-" from human_readable when called with None or NaN

---

gov_uk_dashboards/colours.py
setup.py

While working on another ticket, we found that the light blue on the ONS Accessible Colours had been set up incorrectly (was just a duplicate of maroon). This sets it to the intended colour.
Also, looks like setup.py wasn't updated last time, so that is also set to the right version number.

Fix ONS Accessible Colour - light blue

---

gov_uk_dashboards/components/plotly/paragraph.py
setup.py
tests/unit_tests/gov_uk_dashboards/components/plotly/test_paragraph.py

Added a new paragraph component to the package, that allows a `<p>` to be created with one of 3 preset sizes (Lead, Default, Small)

Added a new paragraph component

---

gov_uk_dashboards/__init__.py
gov_uk_dashboards/axes.py
gov_uk_dashboards/colours.py
gov_uk_dashboards/components/__init__.py
gov_uk_dashboards/components/plotly/__init__.py
gov_uk_dashboards/components/plotly/details.py
gov_uk_dashboards/components/plotly/html_list.py
gov_uk_dashboards/figures/__init__.py
gov_uk_dashboards/figures/enums/__init__.py
gov_uk_dashboards/figures/styles/__init__.py
gov_uk_dashboards/formatting/__init__.py
gov_uk_dashboards/formatting/human_readable.py
gov_uk_dashboards/formatting/rounding.py

Our package now has quite a lot in it. This makes it hard to know what's there or how to access it without reading through the repo/downloading it and having a look. It'd be better if users had some documentation of what it contained.
As such, this PR updates the `__init__.py`s to do 3 things:
- Provide additional documentation to users of the packages through docstrings.
- If you hover over an imported module, it will explain what it contains with a short description of each module/function.
- ![image](https://user-images.githubusercontent.com/97545171/168611550-5d2373c8-0406-459c-ad25-bf62c14df7c9.png)
- Simplify imports - where redundant names existed, these are imported in the parent module. This should make the package a little less cumbersome to use.
- e.g. `from …

Update __init__.py's to simplify imports and provide documentation to users

---

environment.yml
gov_uk_dashboards/components/plotly/__init__.py
gov_uk_dashboards/components/plotly/captioned_figure.py
gov_uk_dashboards/components/plotly/graph.py
requirements.txt
setup.py

Implement a generic captioned figure following the model in the Local Government dashboard. This displays a plotly figure with an attached caption which is not normally displayed but is available to be read by screen readers. This is wrapped in a html `<figure>` element to aid assistive technologies.

Add accessible captioned_figure component

---

gov_uk_dashboards/components/plotly/card.py
gov_uk_dashboards/components/plotly/card_full_width.py
gov_uk_dashboards/components/plotly/row_component.py
setup.py

Signed-off-by: Jordan Hall <jordan@libertyware.co.uk>

fix: row and card should always be a div

---

gov_uk_dashboards/components/plotly/captioned_figure.py

To fix issue with displaying jitters on mobile, added option to captioned_figure to only show on desktop and otherwise should caption.

Added option to captioned_figure for displaying figure on desktop only

---

gov_uk_dashboards/components/plotly/side_navbar.py
setup.py

Add extra class to sidebar navigation component
Remove redundant `<ul>` component from the children of the Nav component
Before 
After

Add extra class to sidebar navigation component

---

gov_uk_dashboards/components/plotly/filter_panel.py
setup.py

Add sub-title for filter panel to allow it to be changed on individual dashboard pages

Filter panel ux

---

gov_uk_dashboards/components/plotly/table.py
setup.py

Modify table to allow for different behaviour of short tables (header doesn't scroll) and long tables (header does scroll). 
Removed include_headers argument as it isn't used for any of our tables (in LG or housing).

modify table to fix scrolling header issue

---

setup.py

Change incorrectly set package version to 4.17.0 after starting minor version from 1 instead of 0

Change incorrectly set package version to 4.17.0

---

gov_uk_dashboards/assets/dashboard.css

Previously this was an opt-in for both the income and Ofsted graph.
We've tested this change against all charts within our dashboards and it results in all legends have an improved (larger) size.
Old legend size:
New legend size:

Generalize the icon size increase for all graphs

---

gov_uk_dashboards/components/plotly/side_navbar.py
setup.py

Margin added around list items for nav bar.
(some changes in screenshot come from local government dashboard PR)
Before:

Increase spacing between nav bar elements

---

.github/workflows/check-before-merging.yml

Add action to check formatting of setup.py
We believe this will be valuable because of an error when releasing v6.2.0 where we made a typo within the `install_requires` list.
This is the error that `setup.py check` would have given if we'd had this GitHub Action installed at the time:
```
error in gov_uk_dashboards setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Parse error at "'=0.2.0'": Expected stringEnd
```
Adding this check should reduce the amount of time wasted in the future if this typo is ever made again.

Add action to check formatting of setup.py

---

README.md
gov_uk_dashboards/assets/dashboard.css
scss/dashboard.scss
setup.py

CSS refactoring and update to readme to include "npm install" step. 
The classes "govuk-table__cell--date" and "govuk-main-wrapper" were extensions of existing gov-uk classes that weren't being used. As such it was deemed that these modifications were unnecessary.

CSS changes and Readme update

---

gov_uk_dashboards/lib/dap/get_dataframe_from_cds.py
setup.py

Change CDS query function to dashboard tests still run locally. This checks environment variables to see if the data folder is set to "tests" (so that run.py --test-data works) or "STAGE" is set to "testing" (so that pytest works).

Change CDS query function so dashboard tests still run locally

---

gov_uk_dashboards/components/plotly/notification_banner.py
gov_uk_dashboards/components/plotly/warning_text.py
setup.py

Add warning text & notification banner components from gov uk design components

add warning text & notification banner components, update version number

---

gov_uk_dashboards/components/plotly/download_button.py
setup.py

Add a parameter to the download button function so that the text displayed on it can be set. 
This is being done for this ticket https://trello.com/c/zGZf7miA and will also require changes to the building safety dashboard as it is a breaking change.

Be able to set the text on the download button

---

gov_uk_dashboards/components/plotly/table.py
setup.py

Add in default param so that the last row of a table can be unbolded

---

gov_uk_dashboards/components/plotly/__init__.py
gov_uk_dashboards/components/plotly/comparison_la_filter_button.py
setup.py

Add comparison la filter button to package.

add comparison_la_filter_button

---

gov_uk_dashboards/formatting/round_and_add_prefix_and_suffix.py
setup.py
tests/unit_tests/gov_uk_dashboards/formatting/test_round_and_add_prefix_and_suffix.py

Add "round_and_add_prefix_and_suffix" function and tests to round numbers to a given decimal place and includes trailing 0's.
eg. 1.2 to 2dp is 1.20

Format decimal places

---

gov_uk_dashboards/assets/dashboard.css
scss/dashboard.scss
setup.py

Give home page box sizes a consistent look

Home page Box sizes

---

gov_uk_dashboards/assets/dashboard.css
gov_uk_dashboards/components/plotly/html_list.py
gov_uk_dashboards/lib/dap/dap_deployment.py
gov_uk_dashboards/lib/http_headers.py
scss/dashboard.scss
setup.py

- [] Add a descriptive message for this change to the PR
the padding was making the boxes overflow the gov UK container

Removed padding from container

---

gov_uk_dashboards/components/plotly/side_navbar.py
setup.py

The mobile number was being squished to 20%, I've removed the class that caused that only for mobile, I've also removed the optional on the ID pass in, as I don't believe it makes any sense to pass in a None for the id

Removed class that squished mobile navbar

---

gov_uk_dashboards/components/plotly/captioned_figure.py
setup.py

https://trello.com/c/9SFiDOYa
Changes to the way double clicking on a chart behaves.  Previously, a double click on the plot would autoscale the plot or zoom into the data point. This would mean the hidden large data points were displayed. 
Now, when a user double-clicks on a plot, the plot will only zoom out if it has been zoomed in previously.

Modify doubleClick attribute behaviour

---

gov_uk_dashboards/components/plotly/apply_and_reset_filters_buttons.py
setup.py

https://trello.com/c/ef5bD5bN/1896-bug-reset-filters-link-changed-to-button
Fix bug - Reset filters was incorrectly reported as a link to screen reader users. It is now reported as a button.

reset filter button has role type button rather than link

---

gov_uk_dashboards/components/plotly/table.py
setup.py

Previously getting the following warning.  The suggested change fixes it:
``` 
...gov_uk_dashboards\components\plotly\table.py:
78: FutureWarning:
Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as l
abels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
```
Patch to 9.16.4

Fix pandas warning

---

gov_uk_dashboards/assets/dashboard.css
scss/dashboard.scss
setup.py

- update css for grid-container-css & grid-item-css

update css for grid-container-css & grid-item-css

---

gov_uk_dashboards/colours.py
setup.py

- [NA] Include screenshot for any visual changes
Add the three analyis function colour palettes to the colours enums

Add analysis function colours

---

gov_uk_dashboards/assets/dashboard.css
scss/dashboard.scss
setup.py

Add 3 new classes for creating grid layouts & box container layout 
- three_column_grid_layout 
- two_column_grid_layout 
- box_container_layout

Add grid layout and box container layout classes

---

gov_uk_dashboards/assets/dashboard.css
scss/dashboard.scss
setup.py

- [N/A] Include screenshot for any visual changes
Add CSS classes for use on homepage buttons

Add css for homepage

---

gov_uk_dashboards/assets/dashboard.css
gov_uk_dashboards/components/plotly/table.py
scss/dashboard.scss
setup.py

Optimise dashboard for smaller screens & mobile devices:
•	For grid layout classes add css media rule when width is less than 600px so that the grid only has 1 column
•	Make horizontal gap % so that it is in proportion with width
•	Add new context-card-grid-item class 
•	Update table component so that it horizontally scrolls and does not overflow

Optimise for mobile devices and smaller screens

---

gov_uk_dashboards/assets/dashboard.css
gov_uk_dashboards/components/plotly/table.py
scss/dashboard.scss
setup.py

- context card content anchored to top of container by removing justify-content: centre from context-card-grid-item
- added footer option to table from polars df

context card content anchored to top of container

---

gov_uk_dashboards/components/plotly/table.py
setup.py

Tables now have fixed header when scrolling, though now not compatible on mobiles - follow up needed

Scrolly table - fixed headers

---

gov_uk_dashboards/components/plotly/stacked_barchart.py
setup.py

https://trello.com/c/o1uLd5Pj/4023-m-1-x-15-day-15-dev-days-csp-stacked-bar-charts-has-unified-hover-and-ability-to-download-%F0%9F%94%B5
Add option to add total to hovertext

Add total to bar chart hover

---

gov_uk_dashboards/components/leaflet/leaflet_choropleth_map.py
setup.py

- [N/A] Include screenshot for any visual changes
So that colorbar title is positioned correctly when using zoom controls

adjust padding for colorbar title on leaflet choropleth map

---

gov_uk_dashboards/assets/register_maps
setup.py

Map tab bug - fix: TypeError: window.dash_leaflet.getMap is not a function
