communitiesuk/pkg_gov_uk_dashboards

- README.md
- gov_uk_dashboards/components/plotly/graph.py
- setup.py
This fixes our issue with having the layout jump about the place due to dash graph responsiveness being a pain
> Add graph with default size of 450px

- setup.py
- Updated version number as the main version number was updated while working on the branch which I didn't notice
> Updated version number on branch as main changed

- setup.py
Added missing `__init__.py` to new formatting folder
> Fixed missing __init__.py

- gov_uk_dashboards/colours.py
- setup.py
Add ONS accessible colours used in the housing supply benchmarking visualisation.
> Add accessible colours

- .github/pull_request_template.md
Added PR template with task checklist
> Added PR template with task checklist

- gov_uk_dashboards/components/plotly/banners.py
- setup.py
Signed-off-by: Jordan Hall <jordan@libertyware.co.uk>
> fix: repair structure for the banner

- requirements.txt
- setup.py
> dashbootstap components added to requirements

- setup.py
> Upate setup with dash bootstrap components

- setup.py
> Bump version number in setup.py

- gov_uk_dashboards/components/plotly/footer.py
- gov_uk_dashboards/components/plotly/navbar.py
- gov_uk_dashboards/components/plotly/side_navbar.py
- setup.py
This fixes accessibility for the navigation and allow you to add content into the footer
> Footer and Nav fixes for accessibility 

- gov_uk_dashboards/components/plotly/filter_panel.py
- setup.py
Include optional title to filter panel.
> update filter_panel component to include optional title

- gov_uk_dashboards/lib/absolute_path.py
- gov_uk_dashboards/lib/http_headers.py
- gov_uk_dashboards/lib/logging.py
- setup.py
Add functions to package that are common throughout dashboards
> Add functions to package

- gov_uk_dashboards/components/plotly/__init__.py
- gov_uk_dashboards/components/plotly/clear_all_selections_link.py
- setup.py
Add clear_all_selections_link import to init
> Add clear_all_selections_link import to init

- README.md
Add instructions for trying out changes to the package from other repositories to README
> Add instructions for trying out changes to the package from other repositories to README

- README.md
> Reword readme to test dependabot

- setup.py
> replace = with ~= in setup.py

- gov_uk_dashboards/components/plotly/tooltip.py
- setup.py
Add aria-label to tooltip component.
> Tooltip accessibility

- gov_uk_dashboards/components/plotly/key_value_pair.py
- setup.py
- tests/unit_tests/gov_uk_dashboards/components/plotly/test_key_value_pair.py
Add functionality to key_value_pair to handle strings. Create tests
> Key value pair function update and test 

- environment.yml
- setup.py
Add `python-build` import to `environment.yml` which is used to generate the compiled package.
How our package looks on the TestPyPI: https://test.pypi.org/project/gov-uk-dashboards/
> Include descriptions in setup.py so README displays on pypi website

- .github/workflows/deployment.yml
- setup.py
Add deployment workflow to deploy package to test PyPI and PyPI
> add deployment to PyPI workflow and update package version

- .github/workflows/deployment.yml
> update yml syntax

- .github/workflows/deployment.yml
> update workflow trigger

- README.md
> Update README.md now that package is published to PyPI

- gov_uk_dashboards/lib/dap/__init__.py
- gov_uk_dashboards/lib/dap/dap_deployment.py
- setup.py
> Add scripts used to deploy code to DAP hosting area

- gov_uk_dashboards/lib/dap/get_dataframe_from_cds.py
- setup.py
> Remove values from connection string

- README.md
- setup.py
> update read me

- gov_uk_dashboards/lib/dap/get_dataframe_from_cds.py
- setup.py
Update get_dataframe_from_cds to recognise all exceptions.
> Gov pass debug

- README.md
- setup.py
> tidy readme

- gov_uk_dashboards/lib/enable_basic_auth.py
- setup.py
Check for username and password in basic_auth function
> Update basic auth function

- gov_uk_dashboards/components/plotly/side_navbar.py
- setup.py
> Nav accessibility fix

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
> Spike if no df dashboard

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
Add grid-item-css and grid-container-css classes.
> add grid css

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
> Add css for table formatting

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
update column width css for Edge compatibility
> update column width css for Edge compatibility

- gov_uk_dashboards/components/plotly/download_button.py
- setup.py
Added an optional id variable to download_button()
> Add optional id variable to dropdown

- gov_uk_dashboards/assets/dashboard.css
- gov_uk_dashboards/components/plotly/notification_banner.py
- scss/dashboard.scss
- setup.py
Add new class to package for use when using a notification banner directly underneath filter panel.
Update notification banner component to pass in classname and style - with default parameters.
> Add new classes

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
Reduce button spacing to negative value
> Button margin

- gov_uk_dashboards/components/plotly/side_navbar.py
- setup.py
Add aria-current true to side navbar and update package number
> add aria-current true to side navbar

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
Add class that hides checkboxes on small screens
> Add class that hides checkboxes on small screens

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
Add visually hidden class to package.
> add visually-hidden class

- gov_uk_dashboards/components/plotly/warning_text.py
- setup.py
Add style parameter to warning message to allow for inline styling.
> Add style prop warning text

- gov_uk_dashboards/template.html
- setup.py
Removed reference to DLUHC in title.
Added div section for accessibility purposes.
Updated version to 9.18.0
> Update html template

- gov_uk_dashboards/components/plotly/header.py
- setup.py
> add header file and update package

- gov_uk_dashboards/components/plotly/phase_banner.py
- setup.py
https://trello.com/c/0u9Mj6r9
Add an arg to allow the link to open in a new window. Default behaviour unchanged
> add default arg so can open link in new window

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
https://trello.com/c/96aPcUgG
Add pointer cursor class
> add pointer cursor class

- .github/workflows/deployment.yml
> comment out publishing to test pypi

- .github/workflows/deployment.yml
- setup.py
> increment version and uncomment

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
> add css class for legend cursor

- .github/workflows/deployment.yml
> comment out publish to test pypi

- .github/workflows/deployment.yml
- setup.py
> uncomment deploy to test pypi

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
Update css to include classes for the changed from box.
> Changed from box css

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
Add css class to override table top padding
> add css class for table padding

- gov_uk_dashboards/assets/dashboard.css
- gov_uk_dashboards/components/plotly/__init__.py
- gov_uk_dashboards/components/plotly/download_button.py
- scss/dashboard.scss
- setup.py
https://trello.com/c/tWQZEfZk
update style of download button
> update style of download button

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
Add table classes to allow for a table to have title and subtitle with custom formatting.
- govuk-table__caption--m.margin-if-subtitle
- govuk-table__caption.custom-subtitle
> Table classes

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
- [NA] Run `black ./` locally
- [NA] Run `pylint gov_uk_dashboards` locally
- [NA] Run `python -u -m pytest --headless tests` locally
- [NA] Include screenshot for any visual changes
Add css class allowing different card width
> Add css class allowing different card width

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
Add text-no-transform class for use in change
> text-no-transform class

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
Add column layout class where first col is twice second
> Add column layout class

- gov_uk_dashboards/components/plotly/banners.py
- setup.py
- [NA] Include screenshot for any visual changes
Add style to message banner component
> Add style to message banner

- gov_uk_dashboards/assets/dashboard.css
- gov_uk_dashboards/components/plotly/header.py
- scss/dashboard.scss
- setup.py
- Update header component to use class for strong component
- Add fix-width class to CSS
> update header component to use class for strong component

- gov_uk_dashboards/components/plotly/header.py
- setup.py
update header component - strong_class applied to div, as otherwise box is always fixed width
> add strong_class to div

- gov_uk_dashboards/components/plotly/header.py
- setup.py
add default arg to header comp to change background colour
> add default arg to header comp to change background colour

- gov_uk_dashboards/assets/dashboard.css
- package-lock.json
- scss/dashboard.scss
- setup.py
> Update cookie banner css

- setup.py
> Upgrade version

- gov_uk_dashboards/components/plotly/banners.py
- setup.py
- [N/A] Include screenshot for any visual changes
Remove bold from banner text.
> Remove bold text from banner

- gov_uk_dashboards/components/plotly/card.py
- gov_uk_dashboards/components/plotly/row_component.py
- gov_uk_dashboards/components/plotly/table.py
- setup.py
Create table from polars component
> Remove padding

- gov_uk_dashboards/components/plotly/table.py
- setup.py
Updates the table to make table headers sticky for when the table is scrollable.
> Scrollable table

- gov_uk_dashboards/components/plotly/table.py
- setup.py
table_from_polars_dataframe: add columns_to_right_align paramter to right align this columns content.
> table right align param

- gov_uk_dashboards/assets/dashboard.css
- scss/dashboard.scss
- setup.py
Widen border and slightly darken cards
> Wider border

- gov_uk_dashboards/formatting/human_readable.py
- setup.py
- tests/unit_tests/gov_uk_dashboards/formatting/test_format_as_human_readable.py
- [ x] Include screenshot for any visual changes
Update format human readable function to format negative numbers
> Format negative values to human readable

- gov_uk_dashboards/formatting/rounding.py
- setup.py
Amend rounding to deal with negative numbers
> Amend rounding to deal with negative numbers

- gov_uk_dashboards/assets/dashboard.css
- gov_uk_dashboards/components/plotly/table.py
- scss/dashboard.scss
- setup.py
Update table_from_polars_dataframe() to take parameters to allow table to be sorted.
> Sort table

- gov_uk_dashboards/components/plotly/footer.py
- setup.py
> Links to new tab

- constants.py
- gov_uk_dashboards/components/plotly/generate_dash_graph_from_figure.py
- gov_uk_dashboards/components/plotly/stacked_barchart.py
- gov_uk_dashboards/lib/plotting_helper_functions.py
- gov_uk_dashboards/lib/update_layout_bgcolor_margin.py
- setup.py
> Stacked barchart

- gov_uk_dashboards/components/plotly/time_series_chart.py
- setup.py
> Update x axis formatting

- gov_uk_dashboards/components/plotly/time_series_chart.py
- setup.py
> Format x for year

- gov_uk_dashboards/components/plotly/choropleth_map.py
- setup.py
> Map legend

- gov_uk_dashboards/components/plotly/enums.py
- gov_uk_dashboards/components/plotly/time_series_chart.py
- setup.py
> Timeseries

- gov_uk_dashboards/components/plotly/time_series_chart.py
- setup.py
x unified hover parameters added to timeserieschart class
> x unified hover parameters added to timeserieschart class

- gov_uk_dashboards/components/plotly/time_series_chart.py
- setup.py
- [N/A] Include screenshot for any visual changes
> decrease hoverdistance in timeserieschart

- gov_uk_dashboards/components/helpers/plotting_helper_functions.py
- gov_uk_dashboards/components/plotly/time_series_chart.py
- gov_uk_dashboards/constants.py
- setup.py
- Add 3 new parameters to timeseries class: filled_traces_dict, x_unified_hovertemplate, additional_line
- Remove last_2_traces_filled parameter from timeseries class
> Timeseries tweaks

- .github/workflows/check-before-merging.yml
- gov_uk_dashboards/components/plotly/time_series_chart.py
- setup.py
> Legend group

- gov_uk_dashboards/components/leaflet/leaflet_choropleth_map.py
- setup.py
> Leaflet choropleth

- gov_uk_dashboards/assets/custom_map_style_functions.js
- gov_uk_dashboards/assets/dashboard.css
- gov_uk_dashboards/components/leaflet/leaflet_choropleth_map.py
- scss/dashboard.scss
- setup.py
> Map with discrete

- gov_uk_dashboards/components/leaflet/leaflet_choropleth_map.py
- setup.py
> Increase map legend font size

- gov_uk_dashboards/components/helpers/plotting_helper_functions.py
- gov_uk_dashboards/components/leaflet/leaflet_choropleth_map.py
- gov_uk_dashboards/components/plotly/stacked_barchart.py
- gov_uk_dashboards/components/plotly/time_series_chart.py
- setup.py
> Unified hover

- gov_uk_dashboards/components/helpers/display_chart_or_table_with_header.py
- gov_uk_dashboards/components/helpers/get_chart_for_download.py
- gov_uk_dashboards/components/plotly/time_series_chart.py
- gov_uk_dashboards/lib/download_functions/convert_fig_to_image_and_download.py
- gov_uk_dashboards/lib/download_functions/download_csv_with_headers.py
- setup.py
> Footnote timeseries chart

- gov_uk_dashboards/components/helpers/get_chart_for_download.py
- setup.py
> Footnote bug

- gov_uk_dashboards/components/plotly/stacked_barchart.py
- gov_uk_dashboards/formatting/human_readable.py
- setup.py
> Greyed out bar

- gov_uk_dashboards/components/dash/table.py
- setup.py
> Dynamic table header

- gov_uk_dashboards/lib/download_functions/download_csv_with_headers.py
- setup.py
> Update csv download function to get footnote

- gov_uk_dashboards/components/plotly/time_series_chart.py
- setup.py
> add 2 extra markers to time series chart

- gov_uk_dashboards/components/leaflet/leaflet_choropleth_map.py
- setup.py
> Default map zoom

- gov_uk_dashboards/components/dash/table.py
- gov_uk_dashboards/formatting/text_functions.py
- setup.py
> Add functionality to add ids to table rows

- gov_uk_dashboards/lib/download_functions/download_csv_with_headers.py
- setup.py
> fix bug when data is a str not None

- gov_uk_dashboards/components/dash/main_content.py
- setup.py
> Add id to main content

- gov_uk_dashboards/components/dash/download_button.py
- gov_uk_dashboards/components/dash/heading.py
- gov_uk_dashboards/components/dash/phase_banner.py
- gov_uk_dashboards/components/helpers/display_chart_or_table_with_header.py
- gov_uk_dashboards/components/plotly/stacked_barchart.py
- gov_uk_dashboards/components/plotly/time_series_chart.py
- setup.py
> Download all data

- gov_uk_dashboards/components/dash/header.py
- setup.py
> Mobile menu button

- gov_uk_dashboards/lib/datetime_functions/datetime_functions.py
- setup.py
> Fin jan datetime
